version: '3.8'
services:
  admin:
    image: rakibrifat/admin:latest
    ports:
      - "81:80"
    deploy:
      replicas: 3
  superuser:
    image: rakibrifat/superuser:latest
    ports:
      - "82:80"
    deploy:
      replicas: 3
  normaluser:
    image: rakibrifat/normaluser:latest
    ports:
      - "83:80"
    deploy:
      replicas: 3
  
